### ISSUE TITLE
Make pre-release-tests.yml file

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-dart#8]
During the [pre-release week](https://github.com/meilisearch/integration-guides/blob/master/guides/pre-release-week.md) (concerning only the Meili team, don't bother with the details) I need a CI running against the latest <ins>RC</ins> of MeiliSearch (and not the `latest` image). This RC is
Since the CIs of this package run in a Dart container, I don't know how to specify a dynamic variable (get by a script) to define which MeiliSearch version I would like to start.

See the example in the Ruby SDK CI: 
https://github.com/meilisearch/meilisearch-ruby/blob/2ce58bdda136c1b672fbbbcdefb41f49a69d85c4/.github/workflows/pre-release-tests.yml#L23-L26

The `pre-release-tests.yml` file in this package would start the same:

```yml
# Testing the code base against the MeiliSearch pre-releases
name: Pre-Release Tests

# Will only run for PRs and pushes to bump-meilisearch-v*
on:
  push:
    branches:
      - bump-meilisearch-v*
  pull_request:
    branches:
      - bump-meilisearch-v*

jobs:
  integration-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['2.7', '2.8']
    name: integration-tests-against-rc (dart ${{ matrix.version }})
    
   ...
```

I just currently don't know how to run the latest RC of MeiliSearch in this GitHub Action.

EDIT: Oh maybe use the linux-amd64 assets link to download, unzip and run meilisearch with it: https://github.com/meilisearch/MeiliSearch/releases/download/v0.17.0rc0/meilisearch-macos-amd64
